plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/haydensmac/claude-projects/netlify-teammediahub"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]